### ISSUE TITLE
Auto-completion combo misplaced when list of objects is scrolled down

### ISSUE THREAD

**Issue by BertrandRenault** [pixano/pixano#159] opened 2024-02-16 09:29 UTC
## Bug description

![image](https://github.com/pixano/pixano/assets/112549869/60b288ca-0892-4d5d-8f7f-5975871b5287)

Here we see that the available values combo is below the correct position

## Steps to reproduce

1. Open a dataset image with many objects
2. scroll down the list (the more you scroll, the farther combo goes down, so don't scroll too much else combo is not even visible)
3. edit an object (preferably near top of the screen)
4. open the category choices (delete actual value to have more available values)
-> combo appear at incorrect position (could even be invisible because offscreen)

## Expected behavior

Correct combo position

**Comment by timothee-LJN** [comment] 2024-02-16 11:01
This issue is probably a duplicate of #157

**Comment by BertrandRenault** [comment] 2024-02-16 12:10
I don't think so, here it's related to the relative position depnding on the scroll of object list, whereas #157 is more about z-ordering of the HTML elements

**Closed** 2024-02-20 13:51 UTC
Labels: bug: minor, scope: front, priority: medium
